# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: my-website/
repos:
  - repo: https://github.com/datarootsio/databooks
    rev: 1.2.3
    hooks:
      - id: databooks-meta
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
      - id: black-jupyter
        exclude: .*sum_1to100.ipynb
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args: [-r, ~MD033]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
      - id: nbqa-check-ast
        exclude: .*indent.ipynb
      # - id: nbqa-flake8
      - id: nbqa-isort
      # - id: nbqa-mypy
      # - id: nbqa-pylint
      - id: nbqa-pyupgrade
      # - id: nbqa-yapf
      - id: nbqa-autopep8
        exclude: .*sum_1to(20|100).ipynb
      # - id: nbqa-pydocstyle
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: .eslintrc.json|tsconfig.json
      # - id: pretty-format-json
      #   args: [--autofix]
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.svg$
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
