name: Execute Notebooks

runs:
  using: composite
  steps:
    - name: Install Python Modules
      uses: ./.github/actions/install-python-modules

    - name: Execute Notebooks
      run: npm run execute_notebooks
      shell: bash
