---
name: Black

on:
  push:
  pull_request:
    branches: [main, master]

jobs:
  changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Check Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            black:
              - '**.py,**.ipynb'

  black:
    name: Black
    needs: changes
    if: needs.changes.outputs.black == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Black
        uses: psf/black@stable
        with:
          jupyter: true
