name: Black

on:
  push:
  pull_request:
    branches:
      - [main, master]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Run Black
      - uses: psf/black@stable
        with:
          options: '--exclude="docs/01python/07for/_samples/sum_1to100.ipynb"'
          jupyter: true
