name: Build and Deploy

on:
  push:
    branches: [main, master]

permissions:
  contents: write

concurrency: ci-${{ github.ref }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute Notebooks
        uses: ./.github/actions/execute-notebooks

      - name: Build
        uses: ./.github/actions/build
        with:
          base-url: /

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean-exclude: pr-preview/
          folder: build
