---
name: ESLint

on:
  push:
  pull_request:
    branches: [main, master]

jobs:
  changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Check Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            eslint:
              - '**.js,**.jsx,**.ts,**.tsx'

  eslint:
    name: ESLint
    needs: changes
    if: needs.changes.outputs.eslint == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-eslint

      - name: Install Node Mudules
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm install \
          @typescript-eslint/eslint-plugin \
          @typescript-eslint/parser eslint \
          eslint-config-prettier \
          eslint-plugin-react
        shell: bash

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
