---
name: Formatter

on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            python-files:
              - '**.py,**.pyi,**.ipynb'

  databooks:
    name: Databooks
    needs: changes
    if: needs.changes.outputs.python-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Modules
        uses: ./.github/actions/install_python_modules

      - name: Run Databooks
        run: poetry run databooks meta --no-rm-outs --rm-exec --yes .

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node Mudules
        uses: ./.github/actions/install_node_modules

      - name: Run Prettier
        run: npx prettier --write .

  black:
    name: Black
    needs: changes
    if: needs.changes.outputs.python-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Modules
        uses: ./.github/actions/install_python_modules

      - name: Run Black
        run: poetry run black .

  commit:
    name: Commit
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Formatted!
