---
name: Formatter

on:
  push:
  pull_request:
    branches: [main, master]

jobs:
  changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            python-files:
              - '**.py,**.pyi,**.ipynb'

  databooks:
    name: Databooks
    needs: changes
    if: needs.changes.outputs.python-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Modules
        uses: ./.github/actions/install_python_modules

      - name: Run Databooks
        run: poetry run databooks meta --no-rm-outs --rm-exec --yes .

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node Mudules
        uses: ./.github/actions/install_node_modules

      - name: Run Prettier
        run: npx prettier --write .

  black:
    name: Black
    needs: databooks
    if: needs.changes.outputs.python-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Modules
        uses: ./.github/actions/install_python_modules

      - name: Run Black
        run: poetry run black .

  nbqa-isort:
    name: nqQA-isort
    needs: black
    if: needs.changes.outputs.python-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Modules
        uses: ./.github/actions/install_python_modules

      - name: Run nqQA isort
        run: poetry run nbqa isort .

  nbqa-pyupgrade:
    name: nqQA-pyupgrade
    needs: black
    if: needs.changes.outputs.python-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python Modules
        uses: ./.github/actions/install_python_modules

      - name: Run nqQA pyupgrade
        run: poetry run nbqa pyupgrade .

  pre-commit:
    name: pre-commit
    needs: black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: latest

      - name: Install Python Modules
        uses: ./.github/actions/install_python_modules

      - name: Cache pre-commit
        uses: actions/cache@v3
        id: pre-commit_cache_id
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit environment
        if: steps.pre-commit_cache_id.outputs.cache-hit != 'true'
        run: pre-commit run --all-files

      - name: Run pre-commit
        run: pre-commit run --all-files

  commit:
    name: Commit
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Formatted!
