---
name: Linter

on:
  push:
  pull_request:
    branches: [main, master]

jobs:
  changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            eslint:
              - '**.js,**.jsx,**.ts,**.tsx'
            stylelint:
              - '**.css'

  eslint:
    name: ESLint
    needs: changes
    if: needs.changes.outputs.eslint == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node Mudules
        uses: ./.github/actions/install_node_modules

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  stylelint:
    name: Stylelint
    needs: changes
    if: needs.changes.outputs.stylelint == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node Mudules
        uses: ./.github/actions/install_node_modules

      - name: Run Stylelint
        run: npx stylelint "**/*.css"
