---
name: Notebook Execution Test

on:
  pull_request:
    branches: [main, master]

jobs:
  notebook-execution-test:
    name: Notebook Execution Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Notebooks
        uses: ./.github/actions/execute-notebooks
