name: Notebook Execution Test

on:
  pull_request:

jobs:
  notebook-execution-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute Notebooks
        uses: ./.github/actions/execute-notebooks
