name: Prettier

on:
  push:
  pull_request:
    branches:
      - [master, main]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write .
