---
name: Prettier

on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Node Mudules
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci
        shell: bash

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Formatted!
