name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Execute Notebooks
        uses: ./.github/actions/execute-notebooks

      - name: Make BASE_URL
        uses: actions/github-script@v6
        id: base-url
        with:
          script: |
            const prNumber = "${{ github.event.number }}"; // <pr-number>
            const baseUrl = `/pr-preview/pr-${prNumber}`;
            return baseUrl; // /pr-preview/pr-<pr-number>
          result-encoding: string

      - name: Build
        uses: ./.github/actions/build
        with:
          base-url: ${{ steps.base-url.outputs.result }}

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build
