name: Deploy PR Previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute Notebooks
        uses: ./.github/actions/execute-notebooks

      - name: Make BASE_URL
        uses: actions/github-script@v6
        id: base-url
        with:
          script: |
            const refName = "${{ github.ref_name }}"; // PR_NUMBER/merge
            const prNumber = refName.slice(0, refName.length - 6);
            const baseUrl = `/pr-preview/pr-${prNumber}/`;
            return baseUrl;
          result-encoding: string

      - name: Build
        uses: ./.github/actions/build
        with:
          base-url: ${{ steps.base-url.outputs.result }}

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build
